# To install all of the packages we will need: select all of the lines of code and run them at the same time 
renv::restore(prompt = FALSE)

# install.packages('rgbif')
# install.packages('CoordinateCleaner')
# install.packages('rnaturalearthdata')
# install.packages('tidysdm')
# install.packages('tidyverse')
# install.packages('terra')
# install.packages('sf')
# install.packages('MASS')
# install.packages('patchwork')
# install.packages('tidyterra')
# install.packages('overlapping')
# install.packages('ranger')
# install.packages('xgboost')
# install.packages('DALEX')
# install.packages('exactextractr')